sonar.projectKey=piuba-pescado-erp
sonar.organization=piuba-pescado-erp
sonar.sources=src,app
sonar.exclusions=**/node_modules/**, **/.next/**, **/out/**, **/coverage/**, **/*.config.js, **/*.conf.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json