import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from '@/shared/contexts/QueryProvider';
import { ToastProvider } from '@/shared/contexts/ToastContext';
import { AlertModalProvider } from '@/shared/components/AlertModal';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Envolve toda a aplicação com os providers */}
        <QueryProvider>
          <ToastProvider>
            <AlertModalProvider>
              {children}
            </AlertModalProvider>
          </ToastProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
