export { DetailInfoField, DetailSummaryCard, InfoRow } from './detailBlocks';
export type { DetailInfoFieldProps, DetailSummaryCardProps, InfoRowProps } from './detailBlocks';
export { DetailInfoSection } from './DetailInfoSection';
export type { DetailInfoSectionProps } from './DetailInfoSection';
export { DetailPageHero } from './DetailPageHero';
export type { DetailPageHeroProps } from './DetailPageHero';
export { EntityDetailShell } from './EntityDetailShell';
export type { EntityDetailShellProps } from './EntityDetailShell';
export { EntityDetailMetricsBody } from './EntityDetailMetricsBody';
export type { DetailLabeledValue, EntityDetailMetricsBodyProps } from './EntityDetailMetricsBody';
